{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::362480651898:user/myuser"
      },
      "Action": "sts:AssumeRole"
    }
  ]
